// Canonical demo catalog. This is the single source of truth seeded into
// MongoDB by `bun run seed`; the frontend reads vendors/products/offers back
// out via the catalog server functions (src/lib/api/catalog.ts) instead of
// importing static arrays, so this data is genuinely backend-driven.
import type { Vendor, Product, Offer } from "@/lib/data";

export const seedVendors: Vendor[] = [
  {
    id: "tea-point",
    name: "Tea Point",
    cuisine: "Chai & Coffee",
    emoji: "☕",
    rating: 4.6,
    eta: "5-10 min",
    accent: "mango",
    tagline: "Freshly brewed, every 10 minutes",
    counter: "Counter 1",
    hours: "7:00 AM – 8:00 PM",
    specialty: "Kadak masala chai",
    upiId: "teapoint@easyfood",
    highlights: [
      "Brewed to order",
      "Cutting & full glass",
      "Sugar-free option",
    ],
  },
  {
    id: "snack-shack",
    name: "Snack Shack",
    cuisine: "Burgers & Fries",
    emoji: "🍔",
    rating: 4.4,
    eta: "10-15 min",
    accent: "chili",
    tagline: "Hot off the griddle, all day",
    counter: "Counter 2",
    hours: "10:00 AM – 10:00 PM",
    specialty: "Double patty veg burger",
    upiId: "snackshack@easyfood",
    highlights: ["Fresh fry batch", "Extra cheese add-on", "Combo deals"],
  },
  {
    id: "green-bowl",
    name: "Green Bowl",
    cuisine: "Salads & Wraps",
    emoji: "🥗",
    rating: 4.8,
    eta: "8-12 min",
    accent: "mint",
    tagline: "Light meals that keep you going",
    counter: "Counter 3",
    hours: "9:00 AM – 7:00 PM",
    specialty: "Paneer protein wrap",
    upiId: "greenbowl@easyfood",
    highlights: ["Calorie labelled", "Jain option", "No added sugar"],
  },
  {
    id: "tandoor-house",
    name: "Tandoor House",
    cuisine: "North Indian",
    emoji: "🍛",
    rating: 4.5,
    eta: "15-20 min",
    accent: "berry",
    tagline: "Clay-oven classics, family recipes",
    counter: "Counter 4",
    hours: "11:00 AM – 10:30 PM",
    specialty: "Butter paneer with roti",
    upiId: "tandoorhouse@easyfood",
    highlights: ["Live tandoor", "Spice level choice", "Family packs"],
  },
  {
    id: "roll-express",
    name: "Roll Express",
    cuisine: "Rolls & Momos",
    emoji: "🌯",
    rating: 4.3,
    eta: "10-14 min",
    accent: "sky",
    tagline: "Rolled fresh in under 10 minutes",
    counter: "Counter 5",
    hours: "10:30 AM – 9:30 PM",
    specialty: "Egg roll double filling",
    upiId: "rollexpress@easyfood",
    highlights: ["Steamed momos", "Schezwan house sauce", "Quick pickup"],
  },
  {
    id: "sweet-corner",
    name: "Sweet Corner",
    cuisine: "Desserts & Shakes",
    emoji: "🍰",
    rating: 4.7,
    eta: "6-10 min",
    accent: "grape",
    tagline: "Sweet endings and cold shakes",
    counter: "Counter 6",
    hours: "10:00 AM – 10:00 PM",
    specialty: "Red velvet slice",
    upiId: "sweetcorner@easyfood",
    highlights: ["Daily fresh bakes", "Thick shakes", "Eggless desserts"],
  },
];

export const seedProducts: Product[] = [
  {
    id: "p1",
    vendorId: "tea-point",
    name: "Masala Tea",
    price: 20,
    emoji: "🫖",
    veg: true,
    tag: "Bestseller",
  },
  {
    id: "p2",
    vendorId: "tea-point",
    name: "Filter Coffee",
    price: 30,
    emoji: "☕",
    veg: true,
  },
  {
    id: "p3",
    vendorId: "tea-point",
    name: "Butter Bun",
    price: 25,
    emoji: "🥐",
    veg: true,
  },
  {
    id: "p4",
    vendorId: "snack-shack",
    name: "Veg Burger",
    price: 70,
    emoji: "🍔",
    veg: true,
    tag: "Combo",
  },
  {
    id: "p5",
    vendorId: "snack-shack",
    name: "Chicken Burger",
    price: 110,
    emoji: "🍗",
    veg: false,
  },
  {
    id: "p6",
    vendorId: "snack-shack",
    name: "Salted Fries",
    price: 60,
    emoji: "🍟",
    veg: true,
  },
  {
    id: "p7",
    vendorId: "green-bowl",
    name: "Caesar Salad",
    price: 120,
    emoji: "🥗",
    veg: true,
  },
  {
    id: "p8",
    vendorId: "green-bowl",
    name: "Paneer Wrap",
    price: 95,
    emoji: "🌯",
    veg: true,
    tag: "High protein",
  },
  {
    id: "p9",
    vendorId: "green-bowl",
    name: "Fruit Bowl",
    price: 80,
    emoji: "🍉",
    veg: true,
  },
  {
    id: "p10",
    vendorId: "tandoor-house",
    name: "Butter Paneer",
    price: 180,
    emoji: "🍛",
    veg: true,
    tag: "Chef's pick",
  },
  {
    id: "p11",
    vendorId: "tandoor-house",
    name: "Tandoori Roti",
    price: 15,
    emoji: "🫓",
    veg: true,
  },
  {
    id: "p12",
    vendorId: "tandoor-house",
    name: "Chicken Biryani",
    price: 210,
    emoji: "🍚",
    veg: false,
  },
  {
    id: "p13",
    vendorId: "roll-express",
    name: "Veg Momos",
    price: 70,
    emoji: "🥟",
    veg: true,
  },
  {
    id: "p14",
    vendorId: "roll-express",
    name: "Egg Roll",
    price: 85,
    emoji: "🌯",
    veg: false,
    tag: "Spicy",
  },
  {
    id: "p15",
    vendorId: "roll-express",
    name: "Schezwan Noodles",
    price: 100,
    emoji: "🍜",
    veg: true,
  },
  {
    id: "p16",
    vendorId: "sweet-corner",
    name: "Chocolate Shake",
    price: 90,
    emoji: "🥤",
    veg: true,
    tag: "Cold",
  },
  {
    id: "p17",
    vendorId: "sweet-corner",
    name: "Gulab Jamun",
    price: 40,
    emoji: "🍮",
    veg: true,
  },
  {
    id: "p18",
    vendorId: "sweet-corner",
    name: "Red Velvet Slice",
    price: 130,
    emoji: "🍰",
    veg: true,
  },
];

export const seedOffers: Offer[] = [
  {
    id: "o1",
    title: "Flat ₹30 off",
    detail: "On orders above ₹150",
    code: "EASY30",
    accent: "chili",
  },
  {
    id: "o2",
    title: "Chai + Bun ₹40",
    detail: "Only at Tea Point till 11 AM",
    code: "MORNING",
    accent: "mango",
  },
  {
    id: "o3",
    title: "Free delivery",
    detail: "Pickup counter orders",
    code: "PICKUP",
    accent: "mint",
  },
  {
    id: "o4",
    title: "20% off desserts",
    detail: "Sweet Corner, after 4 PM",
    code: "SWEET20",
    accent: "grape",
  },
];

/** One demo login per stall so the vendor dashboard can be exercised without a signup flow. */
export const seedVendorAccounts = seedVendors.map((v) => ({
  name: `${v.name} Staff`,
  email: `${v.id}@vendors.easyfood.demo`,
  password: "vendor123",
  vendorId: v.id,
}));
