/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as authForgotPasswordRouteImport } from "./routes/(auth)/forgot-password"
import { Route as authLoginRouteImport } from "./routes/(auth)/login"
import { Route as authRegisterRouteImport } from "./routes/(auth)/register"
import { Route as legalPrivacyRouteImport } from "./routes/(legal)/privacy"
import { Route as legalTermsRouteImport } from "./routes/(legal)/terms"
import { Route as mainCartRouteImport } from "./routes/(main)/cart"
import { Route as mainCheckoutRouteImport } from "./routes/(main)/checkout"
import { Route as mainNotificationsRouteImport } from "./routes/(main)/notifications"
import { Route as mainProfileRouteImport } from "./routes/(main)/profile"
import { Route as mainSearchRouteImport } from "./routes/(main)/search"
import { Route as AdminIndexRouteImport } from "./routes/admin/index"
import { Route as AdminOrdersRouteImport } from "./routes/admin/orders"
import { Route as AdminUsersRouteImport } from "./routes/admin/users"
import { Route as OrdersIndexRouteImport } from "./routes/orders/index"
import { Route as OrdersOrderIdRouteImport } from "./routes/orders/$orderId"
import { Route as VendorIndexRouteImport } from "./routes/vendor/index"
import { Route as VendorVendorIdRouteImport } from "./routes/vendor/$vendorId"
import { Route as VendorsIndexRouteImport } from "./routes/vendors/index"
import { Route as VendorsVendorIdRouteImport } from "./routes/vendors/$vendorId"
import { Route as AdminUsersUserIdRouteImport } from "./routes/admin/users_.$userId"
import { Route as AdminVendorsIndexRouteImport } from "./routes/admin/vendors/index"
import { Route as AdminVendorsVendorIdRouteImport } from "./routes/admin/vendors/$vendorId"
import { Route as AdminVendorsCreateRouteImport } from "./routes/admin/vendors/create"
import { Route as VendorVendorIdProductsNewRouteImport } from "./routes/vendor/$vendorId/products/new"
import { Route as VendorVendorIdProductsProductIdEditRouteImport } from "./routes/vendor/$vendorId/products/$productId.edit"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: "/(auth)/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: "/(auth)/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: "/(auth)/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const legalPrivacyRoute = legalPrivacyRouteImport.update({
  id: "/(legal)/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any)
const legalTermsRoute = legalTermsRouteImport.update({
  id: "/(legal)/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any)
const mainCartRoute = mainCartRouteImport.update({
  id: "/(main)/cart",
  path: "/cart",
  getParentRoute: () => rootRouteImport,
} as any)
const mainCheckoutRoute = mainCheckoutRouteImport.update({
  id: "/(main)/checkout",
  path: "/checkout",
  getParentRoute: () => rootRouteImport,
} as any)
const mainNotificationsRoute = mainNotificationsRouteImport.update({
  id: "/(main)/notifications",
  path: "/notifications",
  getParentRoute: () => rootRouteImport,
} as any)
const mainProfileRoute = mainProfileRouteImport.update({
  id: "/(main)/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any)
const mainSearchRoute = mainSearchRouteImport.update({
  id: "/(main)/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: "/orders",
  path: "/orders",
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: "/orders/$orderId",
  path: "/orders/$orderId",
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: "/vendor/",
  path: "/vendor/",
  getParentRoute: () => rootRouteImport,
} as any)
const VendorVendorIdRoute = VendorVendorIdRouteImport.update({
  id: "/vendor/$vendorId",
  path: "/vendor/$vendorId",
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: "/vendors/",
  path: "/vendors/",
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsVendorIdRoute = VendorsVendorIdRouteImport.update({
  id: "/vendors/$vendorId",
  path: "/vendors/$vendorId",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: "/users_/$userId",
  path: "/users/$userId",
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendorsIndexRoute = AdminVendorsIndexRouteImport.update({
  id: "/vendors/",
  path: "/vendors/",
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendorsVendorIdRoute = AdminVendorsVendorIdRouteImport.update({
  id: "/vendors/$vendorId",
  path: "/vendors/$vendorId",
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendorsCreateRoute = AdminVendorsCreateRouteImport.update({
  id: "/vendors/create",
  path: "/vendors/create",
  getParentRoute: () => AdminRoute,
} as any)
const VendorVendorIdProductsNewRoute =
  VendorVendorIdProductsNewRouteImport.update({
    id: "/products/new",
    path: "/products/new",
    getParentRoute: () => VendorVendorIdRoute,
  } as any)
const VendorVendorIdProductsProductIdEditRoute =
  VendorVendorIdProductsProductIdEditRouteImport.update({
    id: "/products/$productId/edit",
    path: "/products/$productId/edit",
    getParentRoute: () => VendorVendorIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteWithChildren
  "/forgot-password": typeof authForgotPasswordRoute
  "/login": typeof authLoginRoute
  "/register": typeof authRegisterRoute
  "/privacy": typeof legalPrivacyRoute
  "/terms": typeof legalTermsRoute
  "/cart": typeof mainCartRoute
  "/checkout": typeof mainCheckoutRoute
  "/notifications": typeof mainNotificationsRoute
  "/profile": typeof mainProfileRoute
  "/search": typeof mainSearchRoute
  "/admin/orders": typeof AdminOrdersRoute
  "/admin/users": typeof AdminUsersRoute
  "/orders/$orderId": typeof OrdersOrderIdRoute
  "/vendor/$vendorId": typeof VendorVendorIdRouteWithChildren
  "/vendors/$vendorId": typeof VendorsVendorIdRoute
  "/admin/": typeof AdminIndexRoute
  "/orders/": typeof OrdersIndexRoute
  "/vendor/": typeof VendorIndexRoute
  "/vendors/": typeof VendorsIndexRoute
  "/admin/users/$userId": typeof AdminUsersUserIdRoute
  "/admin/vendors/$vendorId": typeof AdminVendorsVendorIdRoute
  "/admin/vendors/create": typeof AdminVendorsCreateRoute
  "/admin/vendors/": typeof AdminVendorsIndexRoute
  "/vendor/$vendorId/products/new": typeof VendorVendorIdProductsNewRoute
  "/vendor/$vendorId/products/$productId/edit": typeof VendorVendorIdProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/forgot-password": typeof authForgotPasswordRoute
  "/login": typeof authLoginRoute
  "/register": typeof authRegisterRoute
  "/privacy": typeof legalPrivacyRoute
  "/terms": typeof legalTermsRoute
  "/cart": typeof mainCartRoute
  "/checkout": typeof mainCheckoutRoute
  "/notifications": typeof mainNotificationsRoute
  "/profile": typeof mainProfileRoute
  "/search": typeof mainSearchRoute
  "/admin/orders": typeof AdminOrdersRoute
  "/admin/users": typeof AdminUsersRoute
  "/orders/$orderId": typeof OrdersOrderIdRoute
  "/vendor/$vendorId": typeof VendorVendorIdRouteWithChildren
  "/vendors/$vendorId": typeof VendorsVendorIdRoute
  "/admin": typeof AdminIndexRoute
  "/orders": typeof OrdersIndexRoute
  "/vendor": typeof VendorIndexRoute
  "/vendors": typeof VendorsIndexRoute
  "/admin/users/$userId": typeof AdminUsersUserIdRoute
  "/admin/vendors/$vendorId": typeof AdminVendorsVendorIdRoute
  "/admin/vendors/create": typeof AdminVendorsCreateRoute
  "/admin/vendors": typeof AdminVendorsIndexRoute
  "/vendor/$vendorId/products/new": typeof VendorVendorIdProductsNewRoute
  "/vendor/$vendorId/products/$productId/edit": typeof VendorVendorIdProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteWithChildren
  "/(auth)/forgot-password": typeof authForgotPasswordRoute
  "/(auth)/login": typeof authLoginRoute
  "/(auth)/register": typeof authRegisterRoute
  "/(legal)/privacy": typeof legalPrivacyRoute
  "/(legal)/terms": typeof legalTermsRoute
  "/(main)/cart": typeof mainCartRoute
  "/(main)/checkout": typeof mainCheckoutRoute
  "/(main)/notifications": typeof mainNotificationsRoute
  "/(main)/profile": typeof mainProfileRoute
  "/(main)/search": typeof mainSearchRoute
  "/admin/orders": typeof AdminOrdersRoute
  "/admin/users": typeof AdminUsersRoute
  "/orders/$orderId": typeof OrdersOrderIdRoute
  "/vendor/$vendorId": typeof VendorVendorIdRouteWithChildren
  "/vendors/$vendorId": typeof VendorsVendorIdRoute
  "/admin/": typeof AdminIndexRoute
  "/orders/": typeof OrdersIndexRoute
  "/vendor/": typeof VendorIndexRoute
  "/vendors/": typeof VendorsIndexRoute
  "/admin/users_/$userId": typeof AdminUsersUserIdRoute
  "/admin/vendors/$vendorId": typeof AdminVendorsVendorIdRoute
  "/admin/vendors/create": typeof AdminVendorsCreateRoute
  "/admin/vendors/": typeof AdminVendorsIndexRoute
  "/vendor/$vendorId/products/new": typeof VendorVendorIdProductsNewRoute
  "/vendor/$vendorId/products/$productId/edit": typeof VendorVendorIdProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/privacy"
    | "/terms"
    | "/cart"
    | "/checkout"
    | "/notifications"
    | "/profile"
    | "/search"
    | "/admin/orders"
    | "/admin/users"
    | "/orders/$orderId"
    | "/vendor/$vendorId"
    | "/vendors/$vendorId"
    | "/admin/"
    | "/orders/"
    | "/vendor/"
    | "/vendors/"
    | "/admin/users/$userId"
    | "/admin/vendors/$vendorId"
    | "/admin/vendors/create"
    | "/admin/vendors/"
    | "/vendor/$vendorId/products/new"
    | "/vendor/$vendorId/products/$productId/edit"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/privacy"
    | "/terms"
    | "/cart"
    | "/checkout"
    | "/notifications"
    | "/profile"
    | "/search"
    | "/admin/orders"
    | "/admin/users"
    | "/orders/$orderId"
    | "/vendor/$vendorId"
    | "/vendors/$vendorId"
    | "/admin"
    | "/orders"
    | "/vendor"
    | "/vendors"
    | "/admin/users/$userId"
    | "/admin/vendors/$vendorId"
    | "/admin/vendors/create"
    | "/admin/vendors"
    | "/vendor/$vendorId/products/new"
    | "/vendor/$vendorId/products/$productId/edit"
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/(auth)/forgot-password"
    | "/(auth)/login"
    | "/(auth)/register"
    | "/(legal)/privacy"
    | "/(legal)/terms"
    | "/(main)/cart"
    | "/(main)/checkout"
    | "/(main)/notifications"
    | "/(main)/profile"
    | "/(main)/search"
    | "/admin/orders"
    | "/admin/users"
    | "/orders/$orderId"
    | "/vendor/$vendorId"
    | "/vendors/$vendorId"
    | "/admin/"
    | "/orders/"
    | "/vendor/"
    | "/vendors/"
    | "/admin/users_/$userId"
    | "/admin/vendors/$vendorId"
    | "/admin/vendors/create"
    | "/admin/vendors/"
    | "/vendor/$vendorId/products/new"
    | "/vendor/$vendorId/products/$productId/edit"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  legalPrivacyRoute: typeof legalPrivacyRoute
  legalTermsRoute: typeof legalTermsRoute
  mainCartRoute: typeof mainCartRoute
  mainCheckoutRoute: typeof mainCheckoutRoute
  mainNotificationsRoute: typeof mainNotificationsRoute
  mainProfileRoute: typeof mainProfileRoute
  mainSearchRoute: typeof mainSearchRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  VendorVendorIdRoute: typeof VendorVendorIdRouteWithChildren
  VendorsVendorIdRoute: typeof VendorsVendorIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  VendorIndexRoute: typeof VendorIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(auth)/forgot-password": {
      id: "/(auth)/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(auth)/login": {
      id: "/(auth)/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(auth)/register": {
      id: "/(auth)/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(legal)/privacy": {
      id: "/(legal)/privacy"
      path: "/privacy"
      fullPath: "/privacy"
      preLoaderRoute: typeof legalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(legal)/terms": {
      id: "/(legal)/terms"
      path: "/terms"
      fullPath: "/terms"
      preLoaderRoute: typeof legalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(main)/cart": {
      id: "/(main)/cart"
      path: "/cart"
      fullPath: "/cart"
      preLoaderRoute: typeof mainCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(main)/checkout": {
      id: "/(main)/checkout"
      path: "/checkout"
      fullPath: "/checkout"
      preLoaderRoute: typeof mainCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(main)/notifications": {
      id: "/(main)/notifications"
      path: "/notifications"
      fullPath: "/notifications"
      preLoaderRoute: typeof mainNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(main)/profile": {
      id: "/(main)/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof mainProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(main)/search": {
      id: "/(main)/search"
      path: "/search"
      fullPath: "/search"
      preLoaderRoute: typeof mainSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/orders": {
      id: "/admin/orders"
      path: "/orders"
      fullPath: "/admin/orders"
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/users": {
      id: "/admin/users"
      path: "/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    "/orders/": {
      id: "/orders/"
      path: "/orders"
      fullPath: "/orders/"
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/orders/$orderId": {
      id: "/orders/$orderId"
      path: "/orders/$orderId"
      fullPath: "/orders/$orderId"
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/vendor/": {
      id: "/vendor/"
      path: "/vendor"
      fullPath: "/vendor/"
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/vendor/$vendorId": {
      id: "/vendor/$vendorId"
      path: "/vendor/$vendorId"
      fullPath: "/vendor/$vendorId"
      preLoaderRoute: typeof VendorVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/vendors/": {
      id: "/vendors/"
      path: "/vendors"
      fullPath: "/vendors/"
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/vendors/$vendorId": {
      id: "/vendors/$vendorId"
      path: "/vendors/$vendorId"
      fullPath: "/vendors/$vendorId"
      preLoaderRoute: typeof VendorsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/users_/$userId": {
      id: "/admin/users_/$userId"
      path: "/users/$userId"
      fullPath: "/admin/users/$userId"
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/vendors/": {
      id: "/admin/vendors/"
      path: "/vendors"
      fullPath: "/admin/vendors/"
      preLoaderRoute: typeof AdminVendorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/vendors/$vendorId": {
      id: "/admin/vendors/$vendorId"
      path: "/vendors/$vendorId"
      fullPath: "/admin/vendors/$vendorId"
      preLoaderRoute: typeof AdminVendorsVendorIdRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/vendors/create": {
      id: "/admin/vendors/create"
      path: "/vendors/create"
      fullPath: "/admin/vendors/create"
      preLoaderRoute: typeof AdminVendorsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    "/vendor/$vendorId/products/new": {
      id: "/vendor/$vendorId/products/new"
      path: "/products/new"
      fullPath: "/vendor/$vendorId/products/new"
      preLoaderRoute: typeof VendorVendorIdProductsNewRouteImport
      parentRoute: typeof VendorVendorIdRoute
    }
    "/vendor/$vendorId/products/$productId/edit": {
      id: "/vendor/$vendorId/products/$productId/edit"
      path: "/products/$productId/edit"
      fullPath: "/vendor/$vendorId/products/$productId/edit"
      preLoaderRoute: typeof VendorVendorIdProductsProductIdEditRouteImport
      parentRoute: typeof VendorVendorIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminVendorsVendorIdRoute: typeof AdminVendorsVendorIdRoute
  AdminVendorsCreateRoute: typeof AdminVendorsCreateRoute
  AdminVendorsIndexRoute: typeof AdminVendorsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminVendorsVendorIdRoute: AdminVendorsVendorIdRoute,
  AdminVendorsCreateRoute: AdminVendorsCreateRoute,
  AdminVendorsIndexRoute: AdminVendorsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VendorVendorIdRouteChildren {
  VendorVendorIdProductsNewRoute: typeof VendorVendorIdProductsNewRoute
  VendorVendorIdProductsProductIdEditRoute: typeof VendorVendorIdProductsProductIdEditRoute
}

const VendorVendorIdRouteChildren: VendorVendorIdRouteChildren = {
  VendorVendorIdProductsNewRoute: VendorVendorIdProductsNewRoute,
  VendorVendorIdProductsProductIdEditRoute:
    VendorVendorIdProductsProductIdEditRoute,
}

const VendorVendorIdRouteWithChildren = VendorVendorIdRoute._addFileChildren(
  VendorVendorIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  legalPrivacyRoute: legalPrivacyRoute,
  legalTermsRoute: legalTermsRoute,
  mainCartRoute: mainCartRoute,
  mainCheckoutRoute: mainCheckoutRoute,
  mainNotificationsRoute: mainNotificationsRoute,
  mainProfileRoute: mainProfileRoute,
  mainSearchRoute: mainSearchRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  VendorVendorIdRoute: VendorVendorIdRouteWithChildren,
  VendorsVendorIdRoute: VendorsVendorIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  VendorIndexRoute: VendorIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
