/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as CartRouteImport } from "./routes/cart"
import { Route as CheckoutRouteImport } from "./routes/checkout"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as ProfileRouteImport } from "./routes/profile"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as SearchRouteImport } from "./routes/search"
import { Route as OrdersIndexRouteImport } from "./routes/orders.index"
import { Route as OrdersOrderIdRouteImport } from "./routes/orders.$orderId"
import { Route as VendorIndexRouteImport } from "./routes/vendor.index"
import { Route as VendorVendorIdRouteImport } from "./routes/vendor.$vendorId"
import { Route as VendorsIndexRouteImport } from "./routes/vendors.index"
import { Route as VendorsVendorIdRouteImport } from "./routes/vendors.$vendorId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: "/cart",
  path: "/cart",
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: "/checkout",
  path: "/checkout",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: "/orders/$orderId",
  path: "/orders/$orderId",
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: "/vendor/",
  path: "/vendor/",
  getParentRoute: () => rootRouteImport,
} as any)
const VendorVendorIdRoute = VendorVendorIdRouteImport.update({
  id: "/vendor/$vendorId",
  path: "/vendor/$vendorId",
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: "/vendors/",
  path: "/vendors/",
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsVendorIdRoute = VendorsVendorIdRouteImport.update({
  id: "/vendors/$vendorId",
  path: "/vendors/$vendorId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/cart": typeof CartRoute
  "/checkout": typeof CheckoutRoute
  "/login": typeof LoginRoute
  "/profile": typeof ProfileRoute
  "/register": typeof RegisterRoute
  "/search": typeof SearchRoute
  "/orders/$orderId": typeof OrdersOrderIdRoute
  "/vendor/$vendorId": typeof VendorVendorIdRoute
  "/vendors/$vendorId": typeof VendorsVendorIdRoute
  "/orders/": typeof OrdersIndexRoute
  "/vendor/": typeof VendorIndexRoute
  "/vendors/": typeof VendorsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/cart": typeof CartRoute
  "/checkout": typeof CheckoutRoute
  "/login": typeof LoginRoute
  "/profile": typeof ProfileRoute
  "/register": typeof RegisterRoute
  "/search": typeof SearchRoute
  "/orders/$orderId": typeof OrdersOrderIdRoute
  "/vendor/$vendorId": typeof VendorVendorIdRoute
  "/vendors/$vendorId": typeof VendorsVendorIdRoute
  "/orders": typeof OrdersIndexRoute
  "/vendor": typeof VendorIndexRoute
  "/vendors": typeof VendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/cart": typeof CartRoute
  "/checkout": typeof CheckoutRoute
  "/login": typeof LoginRoute
  "/profile": typeof ProfileRoute
  "/register": typeof RegisterRoute
  "/search": typeof SearchRoute
  "/orders/$orderId": typeof OrdersOrderIdRoute
  "/vendor/$vendorId": typeof VendorVendorIdRoute
  "/vendors/$vendorId": typeof VendorsVendorIdRoute
  "/orders/": typeof OrdersIndexRoute
  "/vendor/": typeof VendorIndexRoute
  "/vendors/": typeof VendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/cart"
    | "/checkout"
    | "/login"
    | "/profile"
    | "/register"
    | "/search"
    | "/orders/$orderId"
    | "/vendor/$vendorId"
    | "/vendors/$vendorId"
    | "/orders/"
    | "/vendor/"
    | "/vendors/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/cart"
    | "/checkout"
    | "/login"
    | "/profile"
    | "/register"
    | "/search"
    | "/orders/$orderId"
    | "/vendor/$vendorId"
    | "/vendors/$vendorId"
    | "/orders"
    | "/vendor"
    | "/vendors"
  id:
    | "__root__"
    | "/"
    | "/cart"
    | "/checkout"
    | "/login"
    | "/profile"
    | "/register"
    | "/search"
    | "/orders/$orderId"
    | "/vendor/$vendorId"
    | "/vendors/$vendorId"
    | "/orders/"
    | "/vendor/"
    | "/vendors/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  VendorVendorIdRoute: typeof VendorVendorIdRoute
  VendorsVendorIdRoute: typeof VendorsVendorIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  VendorIndexRoute: typeof VendorIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cart": {
      id: "/cart"
      path: "/cart"
      fullPath: "/cart"
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/checkout": {
      id: "/checkout"
      path: "/checkout"
      fullPath: "/checkout"
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile": {
      id: "/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/search": {
      id: "/search"
      path: "/search"
      fullPath: "/search"
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/orders/": {
      id: "/orders/"
      path: "/orders"
      fullPath: "/orders/"
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/orders/$orderId": {
      id: "/orders/$orderId"
      path: "/orders/$orderId"
      fullPath: "/orders/$orderId"
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/vendor/": {
      id: "/vendor/"
      path: "/vendor"
      fullPath: "/vendor/"
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/vendor/$vendorId": {
      id: "/vendor/$vendorId"
      path: "/vendor/$vendorId"
      fullPath: "/vendor/$vendorId"
      preLoaderRoute: typeof VendorVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/vendors/": {
      id: "/vendors/"
      path: "/vendors"
      fullPath: "/vendors/"
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/vendors/$vendorId": {
      id: "/vendors/$vendorId"
      path: "/vendors/$vendorId"
      fullPath: "/vendors/$vendorId"
      preLoaderRoute: typeof VendorsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  VendorVendorIdRoute: VendorVendorIdRoute,
  VendorsVendorIdRoute: VendorsVendorIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  VendorIndexRoute: VendorIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
